### ISSUE TITLE
[Request] Better repair kits for Police and EMS

### ISSUE THREAD

**Issue by xH0RIZ0Nx** [lastnexusdev/GTA-Athena#10]
**Describe the Request**
Better repair kits for Police and EMS. Currently they only allow 75% of the health to be restored. this gets the car Barely working. Doing a pit at lower speeds (lower than 60) it will wreck your car out almost every time. 

**Additional context**
Another way to fix this is to add something similar to the revive system where after a few minutes you can pay $$ to fix the car.

**Comment by jhina5422** [comment]
This would also be helpful for all public services helicopters and other aircraft as well.

**Comment by lastnexusdev** [comment]
EMS Vehicles will have reduce damage rate no plans to introduce more powerful kits exist or are in the plans atm again we are trying to keep things balance not give ems super items thats why mechanic shops are for for the pit issue a fix is in the works with the lower reduce damage rate
