### ISSUE TITLE
[Request] Fuel tankers that work as fuel tankers

### ISSUE THREAD

**Issue by xH0RIZ0Nx** [lastnexusdev/GTA-Athena#11]
**Describe the Request**
That the pull behind Fuel tankers (found in gas station and docks commonly) fuel cars, Planes, Choppers, Motorcycles ect.  Taka said to put that here

**Additional context**
We could steal fuel trucks as FAMILY

**Comment by lastnexusdev** [comment]
Closed Until we hear back from dev
