### ISSUE TITLE
[BUG] helicopters/airplanes cannot be fueled

### ISSUE THREAD

**Issue by jhina5422** [lastnexusdev/GTA-Athena#15]
**Describe the bug**
helicopters and airplanes cannot be fueled

**To Reproduce**
Steps to reproduce the behavior: attempt to fuel aircraft.

There is also no fuel station at the airport for aircraft to fuel if it were possible for them to fuel.

**Comment by lastnexusdev** [comment]
Fix Atm only One Location In Sandy Shores Can Refuel

**Comment by jhina5422** [comment]
Additional note on this closed item:

Helis fuel by GTA5 model; some models have different fueling locations and so it is more difficult to refuel some models over others. There is nothing we can do about this. helicopters can be fueled and this will be left as is due to the current limitations.
