### ISSUE TITLE
[BUG] The Momo LOL for some reason

### ISSUE THREAD

**Issue by MomoSuperSpeed** [lastnexusdev/GTA-Athena#17]
**Describe the bug**
Prepare for a wall of text lol  Theres a couple of crazy things going on.
For some odd reason for the past couple of days strange happenings has been afoot that seems to only be happening to me.  I have no idea why its just me.  The personal semi truck used for trucking sometimes, and not even every day like every other day, will shut off while driving or just stop moving and will take a few seconds to get it going again.  When this happens theres no fixing it.  It will go on and off like this until a server restart.  Also bodyguarding bugs out sometimes where you will hit insert for a mission and theres nobody to pick up, yet it says you started a mission already.  Relogging fixes this sometimes but sometimes the issue will repeat after relogging.  

Then there is the infamous zombie/nigh invincible police cars.  There seems to be a link between those jobs bugging out and the police cars becoming indestructable drivable wrecks.  I know it is only police cars because while this was happening I got in a regular sedan, drove it off a jump and I instantly exploded when I hit the ground.  So it seems to just be police cars for some reason.  My character is not invincible mind you, just the police car for some reason.  I also noticed I'm able to drive cars that are dead, like when it shows hold shift+E to push, I'm able to drive these cars.  The only cars I cant drive are the ones that are dead dead ie: exploded... 
 Relogging fixes the ability to drive dead/nigh invincible police cars....until the issue mysteriously returns.

**To Reproduce**
Dude, I have no idea why this is going on.  I just started noticing this a few days ago when I was complaining about the truck not working properly while on a job.  Maybe I'm on for too many hours and then this stuff starts happening from god knows what.  It's strange I'm not doing anything crazy.  All I do most of the day is grind that trucker job into the ground until the truck stops working properly.  And when I'm not doing that I'm with most of the other people on the server and then thats when I start noticing stuff, when we are messing around or testing things.

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/109019292/178137769-7ca3e8d9-33c1-454f-9646-bfc2b5569ae4.png)
It looks very dead, the damage meter is even in the red, but this thing was still doing jumps and driving like it was new.  I'm sure would have outlived several regular brand new cars and still have enough life left to be yeeted off a mountain...and survive.

**Comment by lastnexusdev** [comment]
Fixed with removal of trucking
