### ISSUE TITLE
[BUG] vh spawn in hospital doesnt work

### ISSUE THREAD

**Issue by jhina5422** [lastnexusdev/GTA-Athena#2]
**Describe the bug**
vh spawn in hospital doesnt work

Need to move blip for vehicle spawn to ambu garage.
Elevator access from ambu garage to main hospital doesnt exist

**Comment by jhina5422** [comment]
Boss menu in hospital is in invalid location

**Comment by lastnexusdev** [comment]
Please Provide Me The Vector3 and Vector4 of where these 2 items should go

**Comment by jhina5422** [comment]
Access to lower level elevator.
vector3(332.32, -595.67, 43.28)
vector4(332.32, -595.67, 43.28, 243.26)
Access to upper level elevator.
vector3(342.55, -585.44, 28.8)
vector4(342.55, -585.44, 28.8, 67.68)
Vehicle spawn
vector3(316.63, -577.95, 28.8)
vector4(316.63, -577.95, 28.8, 70.03)
Boss menu:
vector3(335.36, -594.64, 44.19)
vector4(335.36, -594.64, 44.19, 250.0)

**Comment by jhina5422** [comment]
Medical armory:
vector3(310.32, -602.98, 43.28)
Medical stash 
vector3(301.8, -599.44, 43.28)

**Comment by jhina5422** [comment]
Medical bed:
vector3(364.98, -585.89, 44.15)

**Comment by jhina5422** [comment]
Need to set remaining spawn beds.

**Comment by lastnexusdev** [comment]
FIXED All Added
