### ISSUE TITLE
[Request] The Armenian Mob!

### ISSUE THREAD

**Issue by xH0RIZ0Nx** [lastnexusdev/GTA-Athena#20]
**Describe the Request**
That the Armenian Mob be added to the gang list and be able to conduct business 

Official wiki: https://gta.fandom.com/wiki/Armenian_Mob 
Known locations: https://gta.fandom.com/wiki/Rogers_Salvage_%26_Scrap

**Additional context**
This group operates differently to the other groups and gangs and would allow people to play another side of crime.

**Comment by lastnexusdev** [comment]
Closed for Now In the works
