### ISSUE TITLE
[Housing] Place stuff in house

### ISSUE THREAD

**Issue by jhina5422** [lastnexusdev/GTA-Athena#23]
Here is a list of things to replace, edit or add.

Fix door: securitydoor set to distance 2
Fix door: maindoor delete
Fix object: Railing 
![qtFndPoS3FqO3LEsrjFOghTcxawrxw](https://user-images.githubusercontent.com/9252840/179385810-55d24499-352d-46ea-8612-05575615ae34.jpg)

Make seat: 
<img width="800" alt="Xf7yE5cMWLguvsmQ38hE44lGCnC6yO" src="https://user-images.githubusercontent.com/9252840/179385782-21176c03-9774-4de5-8c4b-3ee7815982ec.png">
Fill vending machine "candy" : 
<img width="800" alt="OYs9sjKqPKRb7sW0ceuQh3jLTyEzFW" src="https://user-images.githubusercontent.com/9252840/179385838-a32921b3-f870-4cb4-8f61-58bf3504a405.png">
Make drink vending machine "coffee": See object next to this that is coffee maker.
Make seat: 
<img width="800" alt="NHN3ABTQ0H0XRDcxAjlme3zNJSsgES" src="https://user-images.githubusercontent.com/9252840/179385879-f797ad6d-a2a5-4714-bee1-92cb882cb6cd.png">
Define seat textures: 
![hRLsMKGhmOM29TIRPQnbXPWv0DP7xW](https://user-images.githubusercontent.com/9252840/179385890-4df4307e-02ff-4c6a-b398-96eaa633820e.jpg)

**Comment by lastnexusdev** [comment]
placed in LP Closed until its worked on
