### ISSUE TITLE
[Request]Dog the bounty hunters 

### ISSUE THREAD

**Issue by xH0RIZ0Nx** [lastnexusdev/GTA-Athena#24]
**Describe the suggestion**
Be dog the bounty hunter from the A&E hit tv series. Collect both npc and player bounties 

**Link to addons/maps**
https://kevin-scripts.tebex.io/package/5147817

**Screenshots / Videos**
Look at the link u fuk

**Additional context**
Live, laugh, kill momo

**Comment by lastnexusdev** [comment]
Will Be adding Later Today
