### ISSUE TITLE
[Request] Rob bank trucks 

### ISSUE THREAD

**Issue by xH0RIZ0Nx** [lastnexusdev/GTA-Athena#25]
**Describe the suggestion**
The ability to rob bank trucks! More money and interaction with police 

**Link to addons/maps**
https://kevin-scripts.tebex.io/package/5134357

**Screenshots / Videos**
Preview on site

**Additional context**

**Comment by lastnexusdev** [comment]
looking into a similar one https://forum.cfx.re/t/paid-qbcore-esx-bank-truck-robberies-job/4878016

**Comment by lastnexusdev** [comment]
Implemented 8-4-2022
