### ISSUE TITLE
[Request] Shot spotters

### ISSUE THREAD

**Issue by xH0RIZ0Nx** [lastnexusdev/GTA-Athena#26]
**Describe the suggestion**
This script will add a extremely useful tool for LEO and make shooters think twice. This will also fill in for NPC's calling in gun shots.

**Link to addons/maps**
https://github.com/ItzEndah/ShotSpotter

**Screenshots / Videos**
Look at link!!!

**Additional context**
Easy to find Momo now

**Comment by lastnexusdev** [comment]
Added
