### ISSUE TITLE
[BUG] heavy armor 

### ISSUE THREAD

**Issue by xH0RIZ0Nx** [lastnexusdev/GTA-Athena#30]
**Describe the bug**
Heavy armor replaces with player vest with a weird vest

**To Reproduce**
Step 1: Obtained heavy armor 
Step 2: put it on
Step 3: see

**Screenshots / Videos**
Go see mf

**Additional context**
Either replace the vest with one that works right or remove the ability for it to replace vest

**Comment by lastnexusdev** [comment]
Fixed
