### ISSUE TITLE
[BUG] some attachments "don't exist"

### ISSUE THREAD

**Issue by xH0RIZ0Nx** [lastnexusdev/GTA-Athena#31]
**Describe the bug**
Rifle scope and I'm guessing many other attachments cannot be removed or placed on other weapons of the same kind. You get a red error 

**To Reproduce**
Get carbine
Use the attachment menu
Remove rifle scope 
Get error for item does not exist

**Screenshots / Videos**

**Additional context**
Pistol mag, flashlight (any) works fine

**Comment by lastnexusdev** [comment]
Changed Inventory System Awaiting Feedback
