### ISSUE TITLE
[BUG] EUP not working 

### ISSUE THREAD

**Issue by xH0RIZ0Nx** [lastnexusdev/GTA-Athena#33]
**Describe the bug**
EUP clothing not working.

**To Reproduce**
/EUP
Be very surprised

**Screenshots / Videos**
Go see. Fun times 

**Additional context**
EUP offers nice clothing based for GTA police

**Comment by lastnexusdev** [comment]
we are aware of this issue waiting on final clothes setup before we touch eup
