### ISSUE TITLE
[BUG] Bank Robbery Glitched

### ISSUE THREAD

**Issue by jhina5422** [lastnexusdev/GTA-Athena#37]
**Describe the bug**
Bank glitched after robbing diamonds from another bank. Now I cannot grab money. Said rob trolley in old bank even though bank was already robbed. second bank is shown in screenshot.

**To Reproduce**
Steps to reproduce the behavior: Rob one bank without having backpack in hotbar? (thats the only thing I did differently this time than I have before)

**Screenshots / Videos**
https://scrnsht.us/mUfMO8fHFTdWnTyMkKWBq5vuspqMKA.jpg
https://scrnsht.us/Tl4WPHvlElUJUC8CCF47JkFq8bMiYp.png

**Additional context**
This is on my second character.

**Comment by lastnexusdev** [comment]
Is a known issue with the banks Heist again they where not made to be hit one after another they are supposed to be hit and talk to npc then start another by hitting one right after another you never really complete the first one
