### ISSUE TITLE
[BUG] Medical items 

### ISSUE THREAD

**Issue by xH0RIZ0Nx** [lastnexusdev/GTA-Athena#39]
**Describe the bug**
Medical items need images and balanced. Also need a way to buy said items. Bandages may work or may not. You may bleed right after using a bandage. Pain meds are also hit or miss.

**To Reproduce**
1: somehow aquire medical items
2: attempt to use them
3: be disappointed 

**Screenshots / Videos**
Go see for yourself 

**Additional context**

**Comment by lastnexusdev** [comment]
the meds are there for temp fix the full way to actually heal is by going to hospital or having a ems fix you since they have a higher rate ill take a look at it but its supposed to be hit or miss with most of them except bandages
