### ISSUE TITLE
[BUG] Cars duplicate in garage

### ISSUE THREAD

**Issue by jhina5422** [lastnexusdev/GTA-Athena#4]
**Describe the bug**
Cars duplicate in garage when stored. 

**To Reproduce**
Take car to garage; store car; tracked car is stored then car reappears even while in stored status.

**Comment by jhina5422** [comment]
Related to https://github.com/lastnexusdev/GTA-Athena/issues/1#issue-1292360399

**Comment by lastnexusdev** [comment]
Rare Happening atm we are working with Developer To Solve the issue

**Comment by lastnexusdev** [comment]
Seems to be fixed
