### ISSUE TITLE
[BUG]gas station does not exist

### ISSUE THREAD

**Issue by jhina5422** [lastnexusdev/GTA-Athena#40]
**Describe the bug**
gst station does not exist

**To Reproduce**
none

**Screenshots / Videos**
[If applicable, add screenshots to help explain your problem.](https://scrnsht.us/FcLbRsSDJNUK8PX0wnpBcLMpLjC7WU.jpg)

**Additional context**
none

**Comment by lastnexusdev** [comment]
Fixed
