### ISSUE TITLE
[BUG] Death leads to invalid stance

### ISSUE THREAD

**Issue by jhina5422** [lastnexusdev/GTA-Athena#6]
**Describe the bug**
Death/unconcious status leads to invalid stance

**To Reproduce**
die; then revive yourself with r; leads to user being invalid stance

**Comment by jhina5422** [comment]
Due to emote menu

**Comment by lastnexusdev** [comment]
This is due to the new crouch system no longer has the crawl section of the crouch looking into possible fix only way to currently get up is by using the emote menu to do a emote then cancel the emote this will be fixed with our new death system
