### ISSUE TITLE
[BUG] House deco error

### ISSUE THREAD

**Issue by jhina5422** [lastnexusdev/GTA-Athena#7]
**Describe the bug**
Cannot place objects in the house decoration menu due to emote menu

**To Reproduce**
f5 in house deco menu breaks placement

**Additional context**
Unknown cause but likely bugged emote menu.

**Comment by lastnexusdev** [comment]
F5 is mapped in your Game Settings go in to ESC Menu>Keybinds>FiveM Keybinds  and set dpemote to something not f5 or f6
