### ISSUE TITLE
[BUG] 2 Shops one building

### ISSUE THREAD

**Issue by xH0RIZ0Nx** [lastnexusdev/GTA-Athena#8]
**Describe the bug**
Any Market that has NPC has a store that is cheaper and has more items then the normal blue space

**To Reproduce**
step1: some how get money
step2: get a car
step3: drive to market (gas station that is able to enter)
step4: use the ALT menu and click on him
step5: survive 

**Screenshots / Videos**
go see for yourself you lazy bastard

**Additional context**
Love you <3

**Comment by jhina5422** [comment]
Duplicated NPC scripts; not nessecarily a bug more a duplication of scripting error. Still a dev isssue though.

**Comment by lastnexusdev** [comment]
Fixed
